name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup font
        run: |
          mkdir -p $GITHUB_WORKSPACE/fonts
          ./setup-font.sh
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            cheatsheet.typ
        env:
          TYPST_FONT_PATHS: ${{ github.workspace }}/fonts
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            cheatsheet.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"